services:
  - type: web
    name: OnlineShareTradingSystem-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn OnlineShareTradingSystem.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
