# Generated by Django 5.2 on 2025-04-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_stock_api_stockholding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_StockHolding',
            new_name='StockHolding',
        ),
    ]
