# Generated by Django 5.2 on 2025-04-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_rename_api_stockholding_stockholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transaction_pin',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
